server:
  servlet:
    context-path: '/api/currency-service'

currency:
  auto-update:
    urls:
      nbs: https://nbs.sk/export/sk/exchange-rate/latest/csv

spring:
  datasource:
    username: currency-service
    password: password123
    url: jdbc:postgresql://localhost:5433/currency
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
