server:
  servlet:
    context-path: '/api/transaction-service'

spring:
  application:
    name: transaction-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            logger-level: basic
  datasource:
    url: jdbc:postgresql://transaction-db:5434/transaction_db
    username: transaction_user
    password: changemelater
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 30s

clients:
  currency-service:
    url: 'http://localhost:8080/api/currency-service'
