{
 "title": "JAVA",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "system_load_average_1m",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "targets": [
    { "expr": "system_load_average_1m", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jvm_gc_overhead_percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "targets": [
    { "expr": "jvm_gc_overhead_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "process_cpu_usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "executor_pool_size_threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 9, "y": 6 },
   "targets": [
    { "expr": "executor_pool_size_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "sum/count requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum[1m]) / rate(http_server_requests_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "timeout total",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests counter in seconds by status(CAR)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"car:8084\"}[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests errors in seconds(CAR)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"car:8084\"}[$__rate_interval])) by (error)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests counter in seconds by status(DRIVER)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"driver:8082\"}[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests errors in seconds(DRIVER)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"driver:8082\"}[$__rate_interval])) by (error)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests counter in seconds by status(RACE)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"race:8081\"}[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests errors in seconds(RACE)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"race:8081\"}[$__rate_interval])) by (error)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests counter in seconds by status(COMPONENT)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"component:8083\"}[$__rate_interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests errors in seconds(COMPONENT)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=\"component:8083\"}[$__rate_interval])) by (error)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "http_server_requests_seconds_sum/http_server_requests_seconds_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum[1m]) / rate(http_server_requests_seconds_count[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "process_uptime_seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "targets": [
      { "expr": "process_uptime_seconds", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "system_cpu_usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "targets": [
      { "expr": "system_cpu_usage", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "jdbc_connections_active",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "targets": [
      { "expr": "jdbc_connections_active", "legendFormat": "__auto" },
      {
       "expr": "hikaricp_connections_usage_seconds_max",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}