server:
  servlet:
    context-path: '/api/user-service'
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: [ 'prometheus', 'health', 'info' ]

spring:
  datasource:
    url: jdbc:postgresql://user-db:5432/user_db
    username: user_service
    password: changemelater
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: https://oidc.muni.cz/oidc/introspect
          # Martin Kuba's testing resource server
          client-id: d57b3a8f-156e-46de-9f27-39c4daee05e1
          client-secret: fa228ebc-4d54-4cda-901e-4d6287f8b1652a9c9c44-73c9-4502-973f-bcdb4a8ec96a

springdoc:
  swagger-ui:
    oauth:
      # Martin Kuba's testing client
      client-id: 7e02a0a9-446a-412d-ad2b-90add47b0fdd
      client-secret: 48a2b2e3-4b2b-471e-b7b7-b81a85b6eeef22f347f2-3fc9-4e16-8698-3e2492701a89
      scopes:
        - test_read
        - test_write
        - test_1

clients:
  transaction-service:
    #    url: 'http://localhost:8082/api/transaction-service'
    url: 'http://transaction-service:8082/api/transaction-service'

data:
  initialize: true
