server:
  servlet:
    context-path: '/api/user-service'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/user_db
    username: user_service
    password: changemelater
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

clients:
  transaction-service:
    url: 'http://localhost:8080/api/transaction-service'