server:
  servlet:
    context-path: '/api/user-service'


spring:
  datasource:
    url: jdbc:postgresql://user-db:5435/user_db
    username: user_user
    password: changemelater
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
