server:
  servlet:
    context-path: '/api/user-service'
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/user_db
    username: user_service
    password: changemelater
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

clients:
  transaction-service:
    #    url: 'http://localhost:8082/api/transaction-service'
    url: 'http://transaction-service:8082/api/transaction-service'

data:
  initialize: true