server:
  servlet:
    context-path: '/api/analytics-service'

spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:postgresql://localhost:5432/analytics_db
    username: analytics_service
    password: changemelater
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: db/migration